apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-nginx-config
  namespace: web
data:
  jaeger-nginx-config.json: |
    {
      "service_name": "nginx",
      "sampler": {
        "type": "const",
        "param": 100
      },
      "reporter": {
        "logSpans": true,
        "endpoint": "http://linkerd-collector.linkerd:14268/api/traces"
      },
      "headers": {
        "jaegerDebugHeader": "jaeger-debug-id",
        "jaegerBaggageHeader": "jaeger-baggage",
        "traceBaggageHeaderPrefix": "uberctx-"
      },
      "baggage_restrictions": {
        "denyBaggageOnInitializationFailure": false,
        "hostPort": ""
      },
    }
