apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-nginx-config
  namespace: web
data:
  jaeger-nginx-config.json: |
    {
      "service_name": "nginx",
      "sampler": {
        "type": "remote",
        # "param": 0.1,
        # "samplingServerURL": "http://jaeger-agent.observability:5778/sampling"
        "samplingServerURL": "http://otel-collector.observability:5778/sampling"
      },
      "reporter": {
        "logSpans": true,
        "localAgentHostPort": "otel-collector.observability:6831"
      },
      "headers": {
        "jaegerDebugHeader": "jaeger-debug-id",
        "jaegerBaggageHeader": "jaeger-baggage",
        "traceBaggageHeaderPrefix": "uberctx-"
      },
      "baggage_restrictions": {
        "denyBaggageOnInitializationFailure": false,
        "hostPort": ""
      },
    }
