apiVersion: v1
kind: Namespace
metadata:
  name: default
  annotations:
    linkerd.io/inject: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  annotations:
    linkerd.io/inject: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: ambassador
  annotations:
    # enabling this causes ambassador to fail to log to linkerd
    linkerd.io/inject: disabled
    # config.linkerd.io/trace-collector: "linkerd-collector.linkerd:56678"
    # config.alpha.linkerd.io/trace-collector-service-account: linkerd-collector
---
apiVersion: v1
kind: Namespace
metadata:
  name: auth
  annotations:
    linkerd.io/inject: enabled
    # this must be an opencensus collector
    # config.linkerd.io/trace-collector: "linkerd-collector.linkerd:56678"
    # config.alpha.linkerd.io/trace-collector-service-account: linkerd-collector
---
apiVersion: v1
kind: Namespace
metadata:
  name: db
  annotations:
    linkerd.io/inject: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: web
  annotations:
    linkerd.io/inject: enabled
    # config.linkerd.io/trace-collector: "linkerd-collector.linkerd:56678"
    # config.alpha.linkerd.io/trace-collector-service-account: linkerd-collector
---
apiVersion: v1
kind: Namespace
metadata:
  name: loadtest
  annotations:
    linkerd.io/inject: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: poker
  annotations:
    linkerd.io/inject: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: minecraft
  annotations:
    linkerd.io/inject: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: n8n
  annotations:
    linkerd.io/inject: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: poker
  annotations:
    linkerd.io/inject: enabled
    # config.linkerd.io/trace-collector: "linkerd-collector.linkerd:9411"
    # config.alpha.linkerd.io/trace-collector-service-account: linkerd-collector
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  annotations:
    linkerd.io/inject: enabled
