replicaCount: 1
port: 8080

service:
  type: ClusterIP
  port: 8080

persistence:
  enabled: true
  # storageClassName: default
  accessModes:
    - ReadWriteOnce
  size: 2Gi
  # annotations: {}
  # existingClaim:

database:
  type: POSTGRES
  name: predator
  address: postgresql-postgresql-ha-pgpool.db
  username: "cHJlZGF0b3I="
  password: INSECRET

runnerDockerImage: zooz/predator-runner:1.5
runnerCpu: 0.2
runnerMemory: 128
