# https://github.com/cloudhut/charts
secret:
  existingSecret: "kowl0"
kowl:
  config:
    kafka:
      brokers:
        - kafka0-headless:9092

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 100m
    memory: 64Mi
