# https://github.com/bitnami/charts/tree/master/bitnami/kafka

# ny environment variable beginning with KAFKA_CFG_ will be mapped to its corresponding Kafka key.
extraEnvVars:
  - name: KAFKA_CFG_COMPRESSION_TYPE
    value: "gzip"

replicaCount: 1

resources:
  limits:
    cpu: 200m
    memory: 1.4Gi
  requests:
    cpu: 200m
    memory: 1.2Gi

livenessProbe:
  initialDelaySeconds: 300 # java is slow to startup

metrics:
  kafka:
    enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
  jmx:
    enabled: true
  resources:
    limits:
      cpu: 5m
      memory: 64Mi
    requests:
      cpu: 5m
      memory: 64Mi

rbac:
  create: true

persistence:
  enabled: true
  size: 64Gi

service:
  type: ClusterIP

pdb:
  create: true
  ## Min number of pods that must still be available after the eviction
  ##
  #   minAvailable: 1
  ## Max number of pods that can be unavailable after the eviction
  ##
  maxUnavailable: 1

provisioning:
  enabled: true

  topics:
    - name: auto-topic
      partitions: 1
      replicationFactor: 1
      # https://kafka.apache.org/documentation/#topicconfigs
      config:
        # max.message.bytes: 64000
        # flush.messages: 1
    - name: kube-logs
      partitions: 1
      replicationFactor: 1
      # https://kafka.apache.org/documentation/#topicconfigs
      config:
        # max.message.bytes: 64000
        # flush.messages: 1
        compression.type: "gzip"
    - name: otlp_spans
      partitions: 1
      replicationFactor: 1
      # https://kafka.apache.org/documentation/#topicconfigs
      config:
        # max.message.bytes: 64000
        # flush.messages: 1
        compression.type: "gzip"
    - name: otlp_metrics
      partitions: 1
      replicationFactor: 1
      # https://kafka.apache.org/documentation/#topicconfigs
      config:
        # max.message.bytes: 64000
        # flush.messages: 1
        compression.type: "gzip"

zookeeper:
  enabled: true
