persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 64Gi
  annotations: {}

serviceMonitor:
  additionalLabels: {}
  annotations: {}
  enabled: true
  interval: "15s"

config:
  limits_config:
    max_query_series: 1000
  table_manager:
    retention_deletes_enabled: true
    retention_period: "180d"
