---
apiVersion: getambassador.io/v2
kind: FilterPolicy
metadata:
  name: pepper-poker-policy
  namespace: ambassador
spec:
  rules:
    - host: "pepper-poker.wetsnow.com"
      # note that "/" only protects "/" and not "/foo"
      path: "*"
      filters:
        - name: keycloak-pepper-poker-filter ## Enter the Filter name from above
          arguments:
            scope:
              - "email"
              - "profile"
              - "poker"
    # - host: "pepper-poker-grpc.wetsnow.com"
    #   # note that "/" only protects "/" and not "/foo"
    #   path: "/poker.PokerServer/*"
    #   filters:
    #     - name: keycloak-pepper-poker-filter ## Enter the Filter name from above
    #       arguments:
    #         scope:
    #           - "poker" # this scope is required to use this endpoint
    #           - "email"
    #           - "profile"
