apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: pepper-poker.wetsnow.com
  namespace: ambassador
spec:
  acmeProvider:
    email: dant@wetsnow.com
  requestPolicy:
    insecure:
      action: Reject
  hostname: pepper-poker.wetsnow.com
  tlsSecret:
    name: pepper-poker.wetsnow.com
---
apiVersion: getambassador.io/v2
kind: TLSContext
metadata:
  name: pepper-poker.wetsnow.com-context # for the host above
  namespace: ambassador
spec:
  hosts:
    - "pepper-poker.wetsnow.com"
  secret: pepper-poker.wetsnow.com
  alpn_protocols: h2,http/1.1 # required for C# grpc client
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: pepper-poker-grpc.wetsnow.com
  namespace: ambassador
spec:
  acmeProvider:
    email: dant@wetsnow.com
  requestPolicy:
    insecure:
      action: Reject
  hostname: pepper-poker-grpc.wetsnow.com
  tlsSecret:
    name: pepper-poker-grpc.wetsnow.com
---
apiVersion: getambassador.io/v2
kind: TLSContext
metadata:
  name: pepper-poker-grpc.wetsnow.com-context # for the host above
  namespace: ambassador
spec:
  hosts:
    - "pepper-poker-grpc.wetsnow.com"
  secret: pepper-poker-grpc.wetsnow.com
  alpn_protocols: h2,http/1.1 # required for C# grpc client
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: grafana.wetsnow.com
  namespace: ambassador
spec:
  acmeProvider:
    email: dant@wetsnow.com
  hostname: grafana.wetsnow.com
  tlsSecret:
    name: grafana.wetsnow.com
---
apiVersion: getambassador.io/v2
kind: TLSContext
metadata:
  name: grafana.wetsnow.com-context # for the host above
  namespace: ambassador
spec:
  hosts:
    - "grafana.wetsnow.com"
  secret: grafana.wetsnow.com
  alpn_protocols: h2,http/1.1 # required for C# grpc client
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: login.wetsnow.com
  namespace: ambassador
spec:
  acmeProvider:
    email: dant@wetsnow.com
  hostname: login.wetsnow.com
  tlsSecret:
    name: login.wetsnow.com
---
apiVersion: getambassador.io/v2
kind: TLSContext
metadata:
  name: login.wetsnow.com-context # for the host above
  namespace: ambassador
spec:
  hosts:
    - "login.wetsnow.com"
  secret: login.wetsnow.com
  alpn_protocols: h2,http/1.1 # required for C# grpc client
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: do.wetsnow.com
  namespace: ambassador
spec:
  acmeProvider:
    email: dant@wetsnow.com
  hostname: do.wetsnow.com
  tlsSecret:
    name: do.wetsnow.com
---
apiVersion: getambassador.io/v2
kind: TLSContext
metadata:
  name: do.wetsnow.com-context # for the host above
  namespace: ambassador
spec:
  hosts:
    - "do.wetsnow.com"
  secret: do.wetsnow.com
  alpn_protocols: h2,http/1.1 # required for C# grpc client
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: www.wetsnow.com
  namespace: ambassador
spec:
  acmeProvider:
    email: dant@wetsnow.com
  requestPolicy:
    insecure:
      action: Redirect
  hostname: www.wetsnow.com
  tlsSecret:
    name: www.wetsnow.com
# ---
# apiVersion: getambassador.io/v2
# kind: TLSContext
# metadata:
#   name: www.wetsnow.com-context # for the host above
# spec:
#   hosts:
#     - "www.wetsnow.com"
#     - "wetsnow.com"
#   secret: www.wetsnow.com
#   alpn_protocols: h2,http/1.1 # required for C# grpc client
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: n8n.wetsnow.com
  namespace: ambassador
spec:
  acmeProvider:
    email: dant@wetsnow.com
  requestPolicy:
    insecure:
      action: Redirect
  hostname: n8n.wetsnow.com
  tlsSecret:
    name: n8n.wetsnow.com
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: predator.wetsnow.com
  namespace: ambassador
spec:
  acmeProvider:
    email: dant@wetsnow.com
  requestPolicy:
    insecure:
      action: Redirect
  hostname: predator.wetsnow.com
  tlsSecret:
    name: predator.wetsnow.com
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: minecraft.wetsnow.com
  namespace: ambassador
spec:
  acmeProvider:
    email: dant@wetsnow.com
  requestPolicy:
    insecure:
      action: Route
  hostname: minecraft.wetsnow.com
  tlsSecret:
    name: minecraft.wetsnow.com
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: linkerd.wetsnow.com
  namespace: ambassador
spec:
  acmeProvider:
    email: dant@wetsnow.com
  hostname: linkerd.wetsnow.com
  tlsSecret:
    name: linkerd.wetsnow.com
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: jaeger.wetsnow.com
  namespace: ambassador
spec:
  acmeProvider:
    email: dant@wetsnow.com
  hostname: jaeger.wetsnow.com
  tlsSecret:
    name: jaeger.wetsnow.com
