---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: l7-redirect
  namespace: ambassador
spec:
  # hostname: www.wetsnow.com
  # TLS happens at the LB, so disable it here.
  acmeProvider:
    authority: none
  # The default insecure action is Redirect, which is fine.
