---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: admin-mapping
  namespace: ambassador
spec:
  host: ambassador-admin.wetsnow.com
  prefix: /edge_stack/
  rewrite: /edge_stack_ui/edge_stack/
  service: localhost:8500
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: pepper-poker-grpc-server-mapping
  namespace: ambassador
spec:
  prefix: /poker.PokerServer/
  rewrite: /poker.PokerServer/
  service: https://pepper-poker-grpc-service.poker:8443
  # https://github.com/datawire/ambassador/issues/3154
  timeout_ms: 3600000 # required for steaming grpc; 1 hr; 0 is broken!
  connect_timeout_ms: 5000
  grpc: True
  headers:
    :authority: pepper-poker-grpc.wetsnow.com
  resolver: endpoint
  load_balancer:
    policy: least_request
  host: "pepper-poker-grpc.wetsnow.com"
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: pepper-poker-grpcreflect
  namespace: ambassador
spec:
  grpc: true
  prefix: /grpc.
  rewrite: /grpc.
  service: https://pepper-poker-grpc-service.poker:8443
  headers:
    :authority: pepper-poker-grpc.wetsnow.com
  resolver: endpoint
  load_balancer:
    policy: least_request
  host: "pepper-poker-grpc.wetsnow.com"
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: pepper-poker-http-server-mapping
  namespace: ambassador
spec:
  prefix: /
  service: pepper-poker-http-service.poker:8081
  host: "pepper-poker.wetsnow.com"
  resolver: endpoint
  load_balancer:
    policy: least_request
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: grafana
  namespace: ambassador
spec:
  prefix: /
  allow_upgrade:
    - websocket
  host: grafana.wetsnow.com
  resolver: endpoint
  timeout_ms: 80000 # some dashboards load slow?
  service: grafana.monitoring:80
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: login
  namespace: ambassador
spec:
  prefix: /
  host: login.wetsnow.com
  resolver: endpoint
  service: keycloak.auth:8080
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: wetsnow.com
  namespace: ambassador
spec:
  prefix: /
  host: wetsnow.com
  resolver: endpoint
  service: static-web-frontend.web:8080
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: www.wetsnow.com
  namespace: ambassador
spec:
  prefix: /
  host: www.wetsnow.com
  resolver: endpoint
  service: static-web-frontend.web:8080
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: www.dusselskolk.com
  namespace: ambassador
spec:
  prefix: /
  host: www.dusselskolk.com
  resolver: endpoint
  service: static-web-frontend.web:8080
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: dusselskolk.com
  namespace: ambassador
spec:
  prefix: /
  host: dusselskolk.com
  resolver: endpoint
  service: static-web-frontend.web:8080
# ---
# apiVersion: getambassador.io/v2
# kind: Mapping
# metadata:
#   name: n8n.wetsnow.com
#   namespace: ambassador
# spec:
#   prefix: /
#   host: n8n.wetsnow.com
#   resolver: endpoint
#   service: n8n.n8n:80
#   timeout_ms: 0 # required for grpc
#   allow_upgrade:
#     - websocket
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: predator.wetsnow.com
  namespace: ambassador
spec:
  prefix: /
  host: predator.wetsnow.com
  resolver: endpoint
  service: predator.loadtest:8080
  allow_upgrade:
    - websocket
---
# apiVersion: getambassador.io/v2
# kind: Mapping
# metadata:
#   name: linkerd.wetsnow.com
#   namespace: ambassador
# spec:
#   prefix: /
#   host: linkerd.wetsnow.com
#   resolver: endpoint
#   service: linkerd-web.linkerd:8084
#   host_rewrite: linkerd-web.linkerd.svc.cluster.local:8084
#   timeout_ms: 0 # required for grpc
#   allow_upgrade:
#     - websocket
# ---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: jaeger.wetsnow.com
  namespace: ambassador
spec:
  prefix: /
  host: jaeger.wetsnow.com
  resolver: endpoint
  service: jaeger-query.observability:16686
  allow_upgrade:
    - websocket
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: prometheus.wetsnow.com
  namespace: ambassador
spec:
  prefix: /
  host: prometheus.wetsnow.com
  resolver: endpoint
  service: kube-prometheus-prometheus.monitoring:9090
  allow_upgrade:
    - websocket
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: pgadmin.wetsnow.com
  namespace: ambassador
spec:
  prefix: /
  host: pgadmin.wetsnow.com
  resolver: endpoint
  service: pgadmin4.db:80
  allow_upgrade:
    - websocket
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: "404-fallback"
  namespace: ambassador
spec:
  prefix: "/"
  rewrite: "/404/" # This must not map to any existing prefix!
  service: localhost:8500
