---
apiVersion: getambassador.io/v2
kind: FilterPolicy
metadata:
  name: pgadmin-policy
  namespace: ambassador
spec:
  rules:
    - host: "pgadmin.wetsnow.com"
      # note that "/" only protects "/" and not "/foo"
      path: "*"
      filters:
        - name: keycloak-pgadmin-filter ## Enter the Filter name from above
          arguments:
            scope:
              # required scopes
              - "email"
              - "profile"
              - "default"
---
apiVersion: getambassador.io/v2
kind: FilterPolicy
metadata:
  name: kowl-policy
  namespace: ambassador
spec:
  rules:
    - host: "kafka-ui.wetsnow.com"
      # note that "/" only protects "/" and not "/foo"
      path: "*"
      filters:
        - name: keycloak-kowl-filter ## Enter the Filter name from above
          arguments:
            scope:
              # required scopes
              - "email"
              - "profile"
              - "default"
---
apiVersion: getambassador.io/v2
kind: FilterPolicy
metadata:
  name: prometheus-policy
  namespace: ambassador
spec:
  rules:
    - host: "prometheus.wetsnow.com"
      # note that "/" only protects "/" and not "/foo"
      path: "*"
      filters:
        - name: keycloak-prometheus-filter ## Enter the Filter name from above
          arguments:
            scope:
              # required scopes
              - "email"
              - "profile"
              - "default"
---
apiVersion: getambassador.io/v2
kind: FilterPolicy
metadata:
  name: pepper-poker-policy
  namespace: ambassador
spec:
  rules:
    - host: "pepper-poker.wetsnow.com"
      # note that "/" only protects "/" and not "/foo"
      path: "*"
      filters:
        - name: keycloak-pepper-poker-filter ## Enter the Filter name from above
          arguments:
            scope:
              # required scopes
              - "email"
              - "profile"
              - "poker"
