---
apiVersion: getambassador.io/v2
kind: FilterPolicy
metadata:
  name: default-policy
  namespace: ambassador
spec:
  rules:
    - host: "predator.wetsnow.com"
      # note that "/" only protects "/" and not "/foo"
      path: "*"
      filters:
        - name: keycloak-default-filter ## Enter the Filter name from above
          arguments:
            scope:
              # required scopes
              - "email"
              - "profile"
              - "default"
    - host: "linkerd.wetsnow.com"
      # note that "/" only protects "/" and not "/foo"
      path: "*"
      filters:
        - name: keycloak-default-filter ## Enter the Filter name from above
          arguments:
            scope:
              # required scopes
              - "email"
              - "profile"
              - "default"
---
apiVersion: getambassador.io/v2
kind: FilterPolicy
metadata:
  name: pepper-poker-policy
  namespace: ambassador
spec:
  rules:
    - host: "pepper-poker.wetsnow.com"
      # note that "/" only protects "/" and not "/foo"
      path: "*"
      filters:
        - name: keycloak-pepper-poker-filter ## Enter the Filter name from above
          arguments:
            scope:
              # required scopes
              - "email"
              - "profile"
              - "poker"
    # - host: "pepper-poker-grpc.wetsnow.com"
    # note that "/" only protects "/" and not "/foo"
    # path: "*"
    # filters:
    #   - name: keycloak-pepper-poker-filter ## Enter the Filter name from above
    #     arguments:
    #       scope:
    #         - "poker" # this scope is required to use this endpoint
    #         - "email"
    #         - "profile"
---
apiVersion: getambassador.io/v2
kind: FilterPolicy
metadata:
  name: n8n-policy
  namespace: ambassador
spec:
  rules:
    - host: "n8n.wetsnow.com"
      # note that "/" only protects "/" and not "/foo"
      path: "/webhook/*"
    - host: "n8n.wetsnow.com"
      # note that "/" only protects "/" and not "/foo"
      path: "*"
      filters:
        - name: keycloak-n8n-filter ## Enter the Filter name from above
          arguments:
            scope:
              # required scopes
              - "email"
              - "profile"
              - "n8n"
