---
apiVersion: getambassador.io/v2
kind: TracingService
metadata:
  name: tracing
  namespace: ambassador
spec:
  service: "jaeger-collector.observability:9411"
  driver: zipkin
  config: {}
  tag_headers:
    - ":authority"
    - ":path"
  sampling:
    overall: 1 # 100%
