---
# Source: bungeecord/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bungeecord
  labels:
    helm.sh/chart: bungeecord-0.6.1
    app.kubernetes.io/name: bungeecord
    app.kubernetes.io/instance: bungeecord
    app.kubernetes.io/version: "1.7.10"
    app.kubernetes.io/managed-by: Helm
---
# Source: bungeecord/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: bungeecord
  labels:
    helm.sh/chart: bungeecord-0.6.1
    app.kubernetes.io/name: bungeecord
    app.kubernetes.io/instance: bungeecord
    app.kubernetes.io/version: "1.7.10"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  sftp-config: eyJHbG9iYWwiOnsiQ2hyb290Ijp7IkRpcmVjdG9yeSI6IiVoIiwiU3RhcnRQYXRoIjoic2Z0cCJ9LCAiRGlyZWN0b3JpZXMiOiBbInNmdHAiXX0sICJVc2VycyI6IFt7IlVzZXJuYW1lIjogIm1pbmVjcmFmdCIsICJQYXNzd29yZCI6ICJjaGFuZ2VtZSJ9XX0=
---
# Source: bungeecord/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: bungeecord
  labels:
    helm.sh/chart: bungeecord-0.6.1
    app.kubernetes.io/name: bungeecord
    app.kubernetes.io/instance: bungeecord
    app.kubernetes.io/version: "1.7.10"
    app.kubernetes.io/managed-by: Helm
data:
  config.yml: |
    server_connect_timeout: 5000
    remote_ping_cache: -1
    forge_support: false
    player_limit: 20
    permissions:
      default:
      - bungeecord.command.server
      - bungeecord.command.list
      wetsnow:
      - bungeecord.server.creative
      - bungeecord.server.lobby
      - bungeecord.command.server
      - bungeecord.command.list
      admin:
      - bungeecord.command.alert
      - bungeecord.command.end
      - bungeecord.command.ip
      - bungeecord.command.reload
    timeout: 30000
    log_commands: true
    network_compression_threshold: 256
    online_mode: true
    disabled_commands:
    - disabledcommandhere
    servers:
      lobby:
        address: minecraft-minecraft.minecraft:25565
        motd: '&1Just another BungeeCord - Forced Host'
        restricted: true
      creative:
        address: minecraft-minecraft.minecraft:25565
        motd: '&1Just another BungeeCord - Forced Host'
        restricted: true
    listeners:
    - query_port: 25577
      motd: "&1Bugee server"
      tab_list: GLOBAL_PING
      query_enabled: false
      proxy_protocol: true
      ping_passthrough: false
      priorities:
        - creative
      bind_local_address: true
      host: 0.0.0.0:25577
      max_players: 20
      tab_size: 60
      forced_hosts: {}
      force_default_server: true
    ip_forward: true
    remote_ping_timeout: 5000
    prevent_proxy_connections: false
    groups:
      MrWetsnow:
      - admin
      - wetsnow
    connection_throttle: 4000
    connection_throttle_limit: 3
    log_pings: true
---
# Source: bungeecord/templates/persistentvolumeclaim.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bungeecord
  labels:
    helm.sh/chart: bungeecord-0.6.1
    app.kubernetes.io/name: bungeecord
    app.kubernetes.io/instance: bungeecord
    app.kubernetes.io/version: "1.7.10"
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
---
# Source: bungeecord/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: bungeecord
  labels:
    helm.sh/chart: bungeecord-0.6.1
    app.kubernetes.io/name: bungeecord
    app.kubernetes.io/instance: bungeecord
    app.kubernetes.io/version: "1.7.10"
    app.kubernetes.io/managed-by: Helm
  annotations: {}
spec:
  type: ClusterIP
  ports:
    - port: 25565
      targetPort: bungeecord
      protocol: TCP
      name: bungeecord
  selector:
    app.kubernetes.io/name: bungeecord
    app.kubernetes.io/instance: bungeecord
---
# Source: bungeecord/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bungeecord
  labels:
    helm.sh/chart: bungeecord-0.6.1
    app.kubernetes.io/name: bungeecord
    app.kubernetes.io/instance: bungeecord
    app.kubernetes.io/version: "1.7.10"
    app.kubernetes.io/managed-by: Helm
  annotations:
    checksum/config: 8dafea4fd6e9c230b43a2fbf426f3b9ec531c6736a7a4e28ede6581a4fbaba01
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bungeecord
      app.kubernetes.io/instance: bungeecord
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bungeecord
        app.kubernetes.io/instance: bungeecord
    spec:
      serviceAccountName: bungeecord
      securityContext: {}
      containers:
        - name: bungeecord
          securityContext: {}
          image: "pasqualet/bungeecord:openj9"
          imagePullPolicy: IfNotPresent
          ports:
            - name: bungeecord
              containerPort: 25577
              protocol: TCP
          volumeMounts:
            - name: server
              mountPath: /server
            - name: config
              mountPath: /server/config.yml
              subPath: config.yml
          livenessProbe:
            tcpSocket:
              port: 25577
          readinessProbe:
            tcpSocket:
              port: 25577
          env:
            - name: TYPE
              value: BUNGEECORD
            - name: MEMORY
              value: 512m
            - name: JVM_OPTS
              value: ""
            - name: PLUGINS
              value: ""
          resources:
            requests:
              memory: 512Mi
      volumes:
        - name: config
          configMap:
            name: bungeecord
        - name: server
          persistentVolumeClaim:
            claimName: bungeecord
