apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: wetsnow-grpc-ingress
  namespace: poker
  annotations:
    kubernetes.io/ingress.global-static-ip-name: global-grpc-ip0
    networking.gke.io/managed-certificates: wetsnow-grpc-certs
    kubernetes.io/ingress.class: "gce"
spec:
  backend:
    serviceName: pepper-poker-grpc-service
    servicePort: 8443
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: pepper-poker-grpc-hc-config
  namespace: poker
spec:
  # https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features
  timeoutSec: 30
  connectionDraining:
    drainingTimeoutSec: 30
  customRequestHeaders:
    headers:
      - "X-Client-Region:{client_region}"
      - "X-Client-City:{client_city}"
      - "X-Client-CityLatLong:{client_city_lat_long}"
  logging:
    enable: true
    sampleRate: 1.0
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 10
    port: 8081 # this is checking the http port, not grpc!
    type: HTTP
    requestPath: /healthz
