# Default helm values for n8n.
# Default values within the n8n application can be found under https://github.com/n8n-io/n8n/blob/master/packages/cli/config/index.ts
n8n:
  encryption_key: "fjjkdsjfsakjfsalfjsdlfjdslkfasjlfas"

secret:
  database:
    postgresdb:
      password: n8n-password

config: # Dict with all n8n json config options
  database:
    type: postgresdb # Type of database to use - Other possible types ['sqlite', 'mariadb', 'mongodb', 'mysqldb', 'postgresdb'] - default: sqlite
    #  tablePrefix:      # Prefix for table names - default: ''
    #  mongodb:
    #    connectionUrl:  # MongoDB Connection URL - default: mongodb://user:password@localhost:27017/database
    postgresdb:
      database: n8n # PostgresDB Database - default: n8n
      host: postgresql-postgresql-ha-pgpool.db # PostgresDB Host - default: localhost
      port: 5432 # PostgresDB Port - default: 5432
      user: n8n # PostgresDB User - default: root
      # schema: # PostgresDB Schema - default: public
      # ssl:
      #   ca: # SSL certificate authority - default: ''
      #   cert: # SSL certificate - default: ''
      #   key: # SSL key - default: ''
      #   rejectUnauthorized: # If unauthorized SSL connections should be rejected - default: true
  host: "n8n.wetsnow.com"
  # port: 443
  protocol: "https"

# https://docs.n8n.io/reference/configuration.html#configuration
extraEnv:
  WEBHOOK_TUNNEL_URL: "https://n8n.wetsnow.com/"

## Common Kubernetes Config Settings
persistence:
  enabled: true
  type: dynamic # what type volume, possible options are [existing, emptyDir, dynamic] dynamic for Dynamic Volume Provisioning, existing for using an existing Claim
  accessModes:
    - ReadWriteOnce
  size: 5Gi
