---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jaeger-monitor
  namespace: observability
  labels:
    release: prometheus
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      service: jaeger-admin-http-service
  endpoints:
    - port: admin-http
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-admin-http-service
  namespace: observability
  labels:
    service: jaeger-admin-http-service
spec:
  ports:
    - port: 14269
      # targetPort: http
      protocol: TCP
      name: admin-http
  selector:
    app: jaeger
  type: ClusterIP
  clusterIP: None # headless service
