---
# otel-config in configMap (1password)
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: observability
  labels:
    app: opentelemetry
    component: otel-collector
    service: otel-collector
spec:
  ports:
    - name: opencensus # Default endpoint for OpenTelemetry legacy grpc receiver.
      port: 55678
      protocol: TCP
      targetPort: 55678
    - name: otlp-leg-grpc # Default endpoint for OpenTelemetry legacy grpc receiver.
      port: 55680
      protocol: TCP
      targetPort: 55680
    - name: otlp-http
      port: 55681 # Default endpoint for OpenTelemetry http receiver.
      targetPort: 55681
    - name: otlp-grpc # Default endpoint for OpenTelemetry grpc receiver
      port: 4317
      targetPort: 4317
    - name: jaeger-grpc # Default endpoint for Jaeger gRPC receiver
      port: 14250
    - name: jaeger-thrift-http # Default endpoint for Jaeger HTTP receiver.
      port: 14268
    - name: zipkin # Default endpoint for Zipkin receiver.
      port: 9411
    - name: metrics # Default endpoint for querying metrics.
      port: 8888
    - name: thrift-binary
      port: 6832
      protocol: UDP
    - name: thrift-compact
      port: 6831
      protocol: UDP
  selector:
    component: otel-collector
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: otelcontribcol
  name: otelcontribcol
  namespace: observability
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otelcontribcol
  labels:
    app: otelcontribcol
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - namespaces
      - namespaces/status
      - nodes
      - nodes/spec
      - pods
      - pods/status
      - replicationcontrollers
      - replicationcontrollers/status
      - resourcequotas
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otelcontribcol
  labels:
    app: otelcontribcol
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otelcontribcol
subjects:
  - kind: ServiceAccount
    name: otelcontribcol
    namespace: observability
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: observability
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 2
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
    spec:
      serviceAccountName: otelcontribcol
      containers:
        - command:
            - "/otelcontribcol"
            - "--config=/conf/otel-collector-config.yaml"
            #           Memory Ballast size should be max 1/3 to 1/2 of memory.
            - "--mem-ballast-size-mib=683"
          image: otel/opentelemetry-collector-contrib:0.19.0
          name: otel-collector
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 400Mi
          ports:
            - containerPort: 55678 # Default endpoint for opencensus
              name: opencensus
            - containerPort: 55679 # Default endpoint for ZPages.
              name: zpages
            - containerPort: 55680 # Default endpoint for OpenTelemetry legacy grpc receiver.
              name: otlp-leg-grpc
            - containerPort: 55681 # Default endpoint for OpenTelemetry http receiver.
              name: otlp-http
            - containerPort: 4317 # Default endpoint for OpenTelemetry grpc receiver
              name: otlp-grpc
            - containerPort: 14250 # Default endpoint for Jaeger HTTP receiver.
              name: jaeger-http-1
            - containerPort: 14268 # Default endpoint for Jaeger HTTP receiver.
              name: jaeger-http-2
            - containerPort: 9411 # Default endpoint for Zipkin receiver.
              name: zpikin
            - containerPort: 8888 # Default endpoint for querying metrics.
              name: metrics
            - containerPort: 6832
              name: thrift-binary
              protocol: UDP
            - containerPort: 6831
              name: thrift-compact
              protocol: UDP

          volumeMounts:
            - name: otel-collector-config-vol
              mountPath: /conf
            - name: otel-jaeger-sampling-config
              mountPath: /etc/jaeger
          #        - name: otel-collector-secrets
          #          mountPath: /secrets
          livenessProbe:
            httpGet:
              path: /
              port: 13133 # Health Check extension default port.
          readinessProbe:
            httpGet:
              path: /
              port: 13133 # Health Check extension default port.
      volumes:
        - name: otel-collector-config-vol
          configMap:
            name: otel-collector-conf
            items:
              - key: otel-collector-config
                path: otel-collector-config.yaml
        - name: otel-jaeger-sampling-config
          configMap:
            name: jaeger-sampling-configuration
            items:
              - key: sampling
                path: jaeger-sampling-config.json
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector-monitor
  namespace: observability
  labels:
    release: prometheus
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      service: otel-collector
  endpoints:
    - port: metrics
