---
postgresql:
  # pdb:
  #   create: true
  #   minAvailable: 1
  existingSecret: postgresql-secret
  # audit:
  #   logConnections: true
  #   logDisconnections: true
  # repmgrLogLevel: DEBUG

  # livenessProbe:
  #   enabled: true
  # readinessProbe:
  #   enabled: true
  #   # initialDelaySeconds: 600

pgpool:
  # enableLogConnections: true
  # enableLogPerNodeStatement: true
  customUsersSecret: postgresql-pgpool-secret

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
# persistence:
#   size: 8Gi
