auth:
  createAdminUser: false

  ## TLS encryption parameters
  ## ref: https://github.com/bitnami/bitnami-docker-keycloak#tls-encryption
  ##

proxyAddressForwarding: true

serviceDiscovery:
  enabled: true
  protocol: kubernetes.KUBE_PING
  properties: []
  transportStack: tcp

cache:
  ## Number of nodes that will replicate cached data
  ##
  ownersCount: 2
  ## Number of nodes that will replicate cached authentication data
  ##
  authOwnersCount: 2

replicaCount: 2

podAnnotations:
  config.linkerd.io/skip-inbound-ports: "7600" # skip keycloak cluster discovery
  config.linkerd.io/skip-outbound-ports: "7600"

containerPorts:
  http: 8080
  https: 8443

## Keycloak containers' liveness and readiness probes.
livenessProbe:
  initialDelaySeconds: 600 # java is slow to startup

service:
  type: ClusterIP
  port: 8080
  httpsPort: 443
  clusterIP: None

rbac:
  create: true
  # required for kube_ping discovery
  rules:
    - apiGroups:
        - ""
      resources:
        - pods
      verbs:
        - get
        - list

pdb:
  create: true
  minAvailable: 1

## Metrics configuration
##
metrics:
  enabled: true

  service:
    port: 9990
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "{{ .Values.metrics.service.port }}"

  serviceMonitor:
    enabled: true

postgresql:
  enabled: false

extraEnvVarsSecret: keycloak-db-secret

externalDatabase:
  enabled: true
  # host set in secret above
  host: "postgresql-postgresql-ha-pgpool.default"
  # values in keycloak-db-secret
